# This is a basic workflow to help you get started with Actions

name: DockerBuild

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "development" branch
    push:
        branches: [ "*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build-and-push-docker-image"
    build-and-push-docker-image:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            -   name: Extract branch name
                shell: bash
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/php\-})"
                id: extract_branch

            -   name: Action Starting Webhook
                uses: indiesdev/curl@v1.1
                with:
                    url: https://docs.dockr.in/webhook/github-actions
                    method: "POST"
                    headers: '{"Content-Type": "application/json"}'
                    body: '{"tag": "${{ steps.extract_branch.outputs.branch }}", "message": "Docker Build Started", "started_by": "${{ github.actor }}", "data": {"Action Id": "${{ github.run_id }}", "Github Repo": "${{ github.repository }}", "Github Workflow": "${{ github.workflow }}", "Github Run Number": "${{ github.run_number }}"}}'
                    timeout: 4000

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Build and push
                uses: docker/build-push-action@v3
                with:
                    context: .
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: sharanvelu/laravel-php:${{ steps.extract_branch.outputs.branch }}

            -   name: Action Completion Webhook
                uses: indiesdev/curl@v1.1
                with:
                    url: https://docs.dockr.in/webhook/github-actions
                    method: "POST"
                    headers: '{"Content-Type": "application/json"}'
                    body: '{"tag": "${{ steps.extract_branch.outputs.branch }}", "message": "Docker Build Completed", "started_by": "${{ github.actor }}", "data": {"Action Id": "${{ github.run_id }}", "Github Workflow": "${{ github.workflow }}"}}'
                    timeout: 4000
